module.exports = {
    CREATE_TODO_TASK: 'CREATE_TODO_TASK',
    CHANGE_TODO_TASK: 'CHANGE_TODO_TASK',
    DONE_TODO_TASK: 'DONE_TODO_TASK',
    DELETE_TODO_TASK: 'DELETE_TODO_TASK',
    GET_TODO_TASKS_FOR_DATE: 'GET_TODO_TASKS_FOR_DATE',
};
