export const CREATE_TODO_TASK = 'CREATE_TODO_TASK';
export const CREATE_TODO_TASK_FULFILLED = 'CREATE_TODO_TASK_FULFILLED';
export const CREATE_TODO_TASK_REJECTED = 'CREATE_TODO_TASK_REJECTED';

export const CHANGE_TODO_TASK = 'CHANGE_TODO_TASK';
export const CHANGE_TODO_TASK_FULFILLED = 'CHANGE_TODO_TASK_FULFILLED';
export const CHANGE_TODO_TASK_REJECTED = 'CHANGE_TODO_TASK_REJECTED';

export const DONE_TODO_TASK = 'DONE_TODO_TASK';
export const DONE_TODO_TASK_FULFILLED = 'DONE_TODO_TASK_FULFILLED';
export const DONE_TODO_TASK_REJECTED = 'DONE_TODO_TASK_REJECTED';

export const DELETE_TODO_TASK = 'DELETE_TODO_TASK';
export const DELETE_TODO_TASK_FULFILLED = 'DELETE_TODO_TASK_FULFILLED';
export const DELETE_TODO_TASK_REJECTED = 'DELETE_TODO_TASK_REJECTED';

export const GET_TODO_TASKS_FOR_DATE = 'GET_TODO_TASKS_FOR_DATE';
export const GET_TODO_TASKS_FOR_DATE_FULFILLED = 'GET_TODO_TASKS_FOR_DATE_FULFILLED';
export const GET_TODO_TASKS_FOR_DATE_REJECTED = 'GET_TODO_TASKS_FOR_DATE_REJECTED';

export const SET_MUTABLE_ITEM_ID = 'SET_MUTABLE_ITEM_ID';
export const SET_MUTABLE_ITEM_DATE = 'SET_MUTABLE_ITEM_DATE';
export const SET_MUTABLE_ITEM_TASK_TEXT = 'SET_MUTABLE_ITEM_TASK_TEXT';
