export const TEST_TYPE = 'TEST_TYPE';
export const TEST_TYPE_SAGA = 'TEST_TYPE_SAGA';
export const TEST_TYPE_SAGA_FULFILLED = 'TEST_TYPE_SAGA_FULFILLED';
export const TEST_TYPE_SAGA_REJECTED = 'TEST_TYPE_SAGA_REJECTED';
